---

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - git
      - python3
      - python3-virtualenv
      - python3-dev
      - build-essential
      - libffi-dev
    state: present

- name: Create directories
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/{{ item }}"
    state: directory
  loop:
    - printer_data
    - printer_data/gcodes
    - printer_data/config
    - printer_data/comms
    - printer_data/logs
  become: false

- name: Clone repository
  ansible.builtin.git:
    repo: https://github.com/Klipper3d/klipper.git
    dest: /home/{{ ansible_user }}/klipper
    version: master
  notify: Restart Klipper service
  become: false

- name: Create virtualenv
  ansible.builtin.pip:
    virtualenv: /home/{{ ansible_user }}/klipper/venv
    requirements: "/home/{{ ansible_user }}/klipper/scripts/klippy-requirements.txt"
  notify: Restart Klipper service
  become: false

- name: Install printer.cfg
  ansible.builtin.copy:
    src: "templates/printer.cfg"
    dest: /home/pi/printer_data/config/printer.cfg
  notify: Restart Klipper service
  become: false

- name: Install remaining config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/pi/printer_data/config/{{ item | basename }}
  notify: Restart Klipper service
  become: false
  with_fileglob: 'templates/printer_*.cfg'

- name: Install service
  ansible.builtin.template:
    src: templates/klipper.service.j2
    dest: /etc/systemd/system/klipper.service
  notify: Restart Klipper service

- name: Enable service
  ansible.builtin.systemd:
    name: klipper.service
    state: started
    enabled: true
