- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  notify: Restart hostname service

# - name: Add authorized key for the 'pi' user
#   ansible.builtin.authorized_key:
#     user: pi
#     key: "{{ ssh_public_key }}"
#     state: present

# - name: Disable password authentication
#   ansible.builtin.lineinfile:
#     path: /etc/ssh/sshd_config
#     regexp: '^#?PasswordAuthentication'
#     line: 'PasswordAuthentication no'
#     state: present
#   notify: Restart SSH service

- name: Make home directory readable
  ansible.builtin.file:
    path: /home/{{ ansible_user }}
    mode: '755'

- name: Upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    
